{{- if not .Values.ldap.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "panopticum.fullname" . }}-ldap
  labels:
    app: {{ template "panopticum.name" . }}
    chart: {{ template "panopticum.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if (and .Values.ldap.enabled .Values.ldap.bind_dn)}}
  dn: {{ .Values.ldap.bind_dn | b64enc | quote }}
  {{- end }}
  {{- if (and .Values.ldap.enabled .Values.ldap.bind_password)}}
  password: {{ .Values.ldap.bind_password | b64enc | quote }}
  {{- end }}
{{- end -}}