{{- if .Values.admin.superuser.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "panopticum.fullname" . }}-superuser
  labels:
    app: {{ template "panopticum.name" . }}
    chart: {{ template "panopticum.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "3"
type: Opaque
data:
  username: {{ .Values.admin.superuser.username | b64enc | quote }}
  password: {{ .Values.admin.superuser.password | b64enc | quote }}
  email: {{ .Values.admin.superuser.email| b64enc | quote}}
{{- end }}