{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "panopticum.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  rules:
      - host: {{ .Values.ingress.host }}
        http:
          paths:
          - backend:
              serviceName: {{ template "panopticum.fullname" . }}-{{ .Values.frontend.service.name}}
              servicePort: {{ .Values.frontend.service.port }}
            path: /(static/.*|favicon.ico)
          - backend:
              serviceName: {{ template "panopticum.fullname" . }}-{{ .Values.backend.service.name}}
              servicePort: {{ .Values.backend.service.port }}
            path: /(.*)
  tls:
  - hosts:
    - panopticum.adc.corp.acronis.com
    secretName: adc-tls
{{- end }}