apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "panopticum.fullname" . }}-frontend
  app: {{ template "panopticum.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        type: frontend
        app: {{ template "panopticum.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: web
        image: nginx:stable-alpine
        volumeMounts:
        - mountPath: /usr/share/nginx/html/static
          name: static-files-panopticum
        {{- if .Values.frontend.resources }}
        resources: {{- toYaml .Values.frontend.resources | nindent 10 }}
        {{- end }}
      initContainers:
      - name: copy-static
        image: {{ template "panopticum.image" . }}
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command:
          - sh
        args:
          - -c
          - "python manage.py collectstatic --noinput && cp -Rf ./static/ /"
        volumeMounts:
          - mountPath: /static
            name: static-files-panopticum
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 250m
      volumes:
      - name: static-files-panopticum
        emptyDir: {}

